const products = {
  electronics: [
    {
      id: 1,
      name: "Smartphone",
      price: 299.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Latest smartphone with all the modern features.",
    },
    {
      id: 2,
      name: "Laptop",
      price: 999.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "High-performance laptop for work and gaming.",
    },
    {
      id: 3,
      name: "Smartwatch",
      price: 199.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Keep track of your fitness and notifications.",
    },
    {
      id: 4,
      name: "Bluetooth Headphones",
      price: 149.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Wireless headphones with superior sound quality.",
    },
    {
      id: 5,
      name: "Gaming Console",
      price: 399.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Next-gen gaming console for ultimate entertainment.",
    },
    {
      id: 6,
      name: "4K Television",
      price: 799.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Experience movies and shows in stunning 4K resolution.",
    },
    {
      id: 7,
      name: "Tablet",
      price: 499.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Portable tablet for work and play on the go.",
    },
    {
      id: 8,
      name: "Wireless Charger",
      price: 49.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Fast wireless charging for your devices.",
    },
    {
      id: 9,
      name: "Smart Home Speaker",
      price: 129.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Voice-controlled speaker for smart home automation.",
    },
    {
      id: 10,
      name: "VR Headset",
      price: 299.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Immerse yourself in virtual reality experiences.",
    },
  ],
  clothing: [
    {
      id: 11,
      name: "T-Shirt",
      price: 19.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Comfortable cotton t-shirt available in various sizes.",
    },
    {
      id: 12,
      name: "Jeans",
      price: 49.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Stylish jeans with a perfect fit.",
    },
    {
      id: 13,
      name: "Jacket",
      price: 89.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Warm and trendy jacket for the colder months.",
    },
    {
      id: 14,
      name: "Sneakers",
      price: 79.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Casual sneakers for everyday wear.",
    },
    {
      id: 15,
      name: "Sunglasses",
      price: 29.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Stylish sunglasses with UV protection.",
    },
    {
      id: 16,
      name: "Dress",
      price: 69.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Elegant dress perfect for formal occasions.",
    },
    {
      id: 17,
      name: "Cap",
      price: 14.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Casual cap for sun protection and style.",
    },
    {
      id: 18,
      name: "Scarf",
      price: 24.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Warm scarf made from soft materials.",
    },
    {
      id: 19,
      name: "Swimsuit",
      price: 34.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Comfortable swimsuit for the beach or pool.",
    },
    {
      id: 20,
      name: "Belt",
      price: 19.99,
      imageUrl: "https://via.placeholder.com/150",
      description: "Leather belt that complements any outfit.",
    },
  ],
};

export default products;
